Clean up test CMakeLists.txt, move pthread order (#1356)
On my ubuntu box using g++ 5.4 and not using the builder image, I keep
running into these build errors:

```
[ 22%] Building CXX object
userspace/libsanalyzer/src/CMakeFiles/sanalyzer.dir/analyzer.cpp.o
/mnt/sf_mstemm/work/src/agent/../agent/dependencies/poco-1.9.0-all/target/lib/libPocoFoundation.a(Thread.o):
In function `Poco::ThreadImpl::runnableEntry(void*)':
Thread.cpp:(.text+0x1ed): undefined reference to `pthread_setspecific'
Thread.cpp:(.text+0x232): undefined reference to `pthread_sigmask'
/mnt/sf_mstemm/work/src/agent/../agent/dependencies/poco-1.9.0-all/target/lib/libPocoFoundation.a(Thread.o):
In function `Poco::ThreadImpl::~ThreadImpl()':
Thread.cpp:(.text+0x65e): undefined reference to `pthread_detach'
/mnt/sf_mstemm/work/src/agent/../agent/dependencies/poco-1.9.0-all/target/lib/libPocoFoundation.a(Thread.o):
In function `Poco::ThreadImpl::joinImpl()':
```

I think the problem is that poco requires some pthread functions, but
since pthread is before poco in the link order, the required functions
aren't included.

Moving pthread to the end of target_link_libraries fixes it.

Also remove a bunch of commented-out libraries that aren't used.