add missing PocoCrypto library
apparently Poco::Crypto is currently linked by means of some subtle side effect.

Removing the only reference to Poco::Crypto::X509Certificate within cm_socket.cpp
will cause the error message shown below.

Explicitly adding Poco::Crypto as a dependency (similar to libPocoNet.a
and libPocoNetSSL.a), the error disappears.

../../../../../docker/builder/../../../agent/dependencies/poco-1.9.0-all/target/lib/libPocoNetSSL.a(SSLManager.o): In function `Poco::Net::SSLManager::initDefaultContext(bool)':
SSLManager.cpp:(.text+0x1e73): undefined reference to `Poco::Crypto::OpenSSLInitializer::OpenSSLInitializer()'
SSLManager.cpp:(.text+0x2ae1): undefined reference to `Poco::Crypto::OpenSSLInitializer::~OpenSSLInitializer()'
SSLManager.cpp:(.text+0x2e29): undefined reference to `Poco::Crypto::OpenSSLInitializer::~OpenSSLInitializer()'
../../../../../docker/builder/../../../agent/dependencies/poco-1.9.0-all/target/lib/libPocoNetSSL.a(SSLManager.o): In function `Poco::Net::uninitializeSSL()':
SSLManager.cpp:(.text+0x4d26): undefined reference to `Poco::Crypto::uninitializeCrypto()'
../../../../../docker/builder/../../../agent/dependencies/poco-1.9.0-all/target/lib/libPocoNetSSL.a(SSLManager.o): In function `Poco::Net::initializeSSL()':
SSLManager.cpp:(.text+0x4b1): undefined reference to `Poco::Crypto::initializeCrypto()'
../../../../../docker/builder/../../../agent/dependencies/poco-1.9.0-all/target/lib/libPocoNetSSL.a(SSLManager.o): In function `Poco::AbstractEvent<Poco::Net::VerificationErrorArgs, Poco::DefaultStrategy<Poco::Net::VerificationErrorArgs, Poco::AbstractDelegate<Poco::Net::VerificationErrorArgs> >, Poco::AbstractDelegate<Poco::Net::VerificationErrorArgs>, Poco::FastMutex>::executeAsyncImpl(Poco::AbstractEvent<Poco::Net::VerificationErrorArgs, Poco::DefaultStrategy<Poco::Net::VerificationErrorArgs, Poco::AbstractDelegate<Poco::Net::VerificationErrorArgs> >, Poco::AbstractDelegate<Poco::Net::VerificationErrorArgs>, Poco::FastMutex>::NotifyAsyncParams const&)':
SSLManager.cpp:(.text._ZN4Poco13AbstractEventINS_3Net21VerificationErrorArgsENS_15DefaultStrategyIS2_NS_16AbstractDelegateIS2_EEEES5_NS_9FastMutexEE16executeAsyncImplERKNS8_17NotifyAsyncParamsE[_ZN4Poco13AbstractEventINS_3Net21VerificationErrorArgsENS_15DefaultStrategyIS2_NS_16AbstractDelegateIS2_EEEES5_NS_9FastMutexEE16executeAsyncImplERKNS8_17NotifyAsyncParamsE]+0x41): undefined reference to `Poco::Crypto::X509Certificate::X509Certificate(Poco::Crypto::X509Certificate const&)'
SSLManager.cpp:(.text._ZN4Poco13AbstractEventINS_3Net21VerificationErrorArgsENS_15DefaultStrategyIS2_NS_16AbstractDelegateIS2_EEEES5_NS_9FastMutexEE16executeAsyncImplERKNS8_17NotifyAsyncParamsE[_ZN4Poco13AbstractEventINS_3Net21VerificationErrorArgsENS_15DefaultStrategyIS2_NS_16AbstractDelegateIS2_EEEES5_NS_9FastMutexEE16executeAsyncImplERKNS8_17NotifyAsyncParamsE]+0x89): undefined reference to `Poco::Crypto::X509Certificate::X509Certificate(Poco::Crypto::X509Certificate const&)'
SSLManager.cpp:(.text._ZN4Poco13AbstractEventINS_3Net21VerificationErrorArgsENS_15DefaultStrategyIS2_NS_16AbstractDelegateIS2_EEEES5_NS_9FastMutexEE16executeAsyncImplERKNS8_17NotifyAsyncParamsE[_ZN4Poco13AbstractEventINS_3Net21VerificationErrorArgsENS_15DefaultStrategyIS2_NS_16AbstractDelegateIS2_EEEES5_NS_9FastMutexEE16executeAsyncImplERKNS8_17NotifyAsyncParamsE]+0xe4): undefined reference to `Poco::Crypto::X509Certificate::X509Certificate(Poco::Crypto::X509Certificate const&)'
SSLManager.cpp:(.text._ZN4Poco13AbstractEventINS_3Net21VerificationErrorArgsENS_15DefaultStrategyIS2_NS_16AbstractDelegateIS2_EEEES5_NS_9FastMutexEE16executeAsyncImplERKNS8_17NotifyAsyncParamsE[_ZN4Poco13AbstractEventINS_3Net21VerificationErrorArgsENS_15DefaultStrategyIS2_NS_16AbstractDelegateIS2_EEEES5_NS_9FastMutexEE16executeAsyncImplERKNS8_17NotifyAsyncParamsE]+0x17d): undefined reference to `Poco::Crypto::X509Certificate::X509Certificate(Poco::Crypto::X509Certificate const&)'
../../../../../docker/builder/../../../agent/dependencies/poco-1.9.0-all/target/lib/libPocoNetSSL.a(Context.o): In function `Poco::Net::Context::~Context()':
Context.cpp:(.text+0x1a): undefined reference to `Poco::Crypto::OpenSSLInitializer::uninitialize()'
../../../../../docker/builder/../../../agent/dependencies/poco-1.9.0-all/target/lib/libPocoNetSSL.a(Context.o): In function `Poco::Net::Context::init(Poco::Net::Context::Params const&)':
Context.cpp:(.text+0x11c8): undefined reference to `Poco::Crypto::OpenSSLInitializer::initialize()'
../../../../../docker/builder/../../../agent/dependencies/poco-1.9.0-all/target/lib/libPocoNetSSL.a(VerificationErrorArgs.o): In function `Poco::Net::VerificationErrorArgs::VerificationErrorArgs(Poco::Net::X509Certificate const&, int, int, std::string const&)':
VerificationErrorArgs.cpp:(.text+0x17): undefined reference to `Poco::Crypto::X509Certificate::X509Certificate(Poco::Crypto::X509Certificate const&)'
../../../../../docker/builder/../../../agent/dependencies/poco-1.9.0-all/target/lib/libPocoNetSSL.a(X509Certificate.o): In function `Poco::Net::X509Certificate::operator=(Poco::Crypto::X509Certificate const&)':
X509Certificate.cpp:(.text+0x5c): undefined reference to `Poco::Crypto::X509Certificate::X509Certificate(Poco::Crypto::X509Certificate const&)'
X509Certificate.cpp:(.text+0x67): undefined reference to `Poco::Crypto::X509Certificate::swap(Poco::Crypto::X509Certificate&)'
X509Certificate.cpp:(.text+0x6f): undefined reference to `Poco::Crypto::X509Certificate::~X509Certificate()'
X509Certificate.cpp:(.text+0x83): undefined reference to `Poco::Crypto::X509Certificate::~X509Certificate()'
../../../../../docker/builder/../../../agent/dependencies/poco-1.9.0-all/target/lib/libPocoNetSSL.a(X509Certificate.o): In function `Poco::Net::X509Certificate::X509Certificate(std::istream&)':
X509Certificate.cpp:(.text+0x1): undefined reference to `Poco::Crypto::X509Certificate::X509Certificate(std::istream&)'
../../../../../docker/builder/../../../agent/dependencies/poco-1.9.0-all/target/lib/libPocoNetSSL.a(X509Certificate.o): In function `Poco::Net::X509Certificate::X509Certificate(std::string const&)':
X509Certificate.cpp:(.text+0x11): undefined reference to `Poco::Crypto::X509Certificate::X509Certificate(std::string const&)'
../../../../../docker/builder/../../../agent/dependencies/poco-1.9.0-all/target/lib/libPocoNetSSL.a(X509Certificate.o): In function `Poco::Net::X509Certificate::X509Certificate(x509_st*)':
X509Certificate.cpp:(.text+0x21): undefined reference to `Poco::Crypto::X509Certificate::X509Certificate(x509_st*)'
../../../../../docker/builder/../../../agent/dependencies/poco-1.9.0-all/target/lib/libPocoNetSSL.a(X509Certificate.o): In function `Poco::Net::X509Certificate::X509Certificate(x509_st*, bool)':
X509Certificate.cpp:(.text+0x34): undefined reference to `Poco::Crypto::X509Certificate::X509Certificate(x509_st*, bool)'
../../../../../docker/builder/../../../agent/dependencies/poco-1.9.0-all/target/lib/libPocoNetSSL.a(X509Certificate.o): In function `Poco::Net::X509Certificate::X509Certificate(Poco::Crypto::X509Certificate const&)':
X509Certificate.cpp:(.text+0x41): undefined reference to `Poco::Crypto::X509Certificate::X509Certificate(Poco::Crypto::X509Certificate const&)'
../../../../../docker/builder/../../../agent/dependencies/poco-1.9.0-all/target/lib/libPocoNetSSL.a(X509Certificate.o): In function `Poco::Net::X509Certificate::~X509Certificate()':
X509Certificate.cpp:(.text+0x91): undefined reference to `Poco::Crypto::X509Certificate::~X509Certificate()'
collect2: error: ld returned 1 exit status
make[2]: *** [userspace/agentone/test/unit-test-agentone] Error 1
make[1]: *** [userspace/agentone/test/CMakeFiles/unit-test-agentone.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....